### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by laulaz** [collective/collective.autopublishing#6]
@tomgross would it be possible to make a new release ?
Or to give me release rights on pypi (user : laz) ?

Thanks a lot !

**Comment by tomgross** [comment]
Hey @laulaz you have permissions on pypi now.

**Comment by tomgross** [comment]
The build is failing BTW. It is not caused by your changes but some versioning conflict.

**Comment by laulaz** [comment]
Thanks @tomgross!

**Comment by laulaz** [comment]
@tomgross I fixed Travis & did a release.
